### ISSUE TITLE
Create input plugin for ESGF Solr CMIP(5/6) data to generate STAC content

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#89]
The ESGF Solr index has many metadata fields which are important for ESGF.

In order for STAC to be seen as a viable alternative, we need to show the community the future and what it looks like.

**Comment by agstephens** [comment]
The suggestion is:
- [x] Understand the basic search capabilities of ESGF (dataset and file level search; querying available facets for search): https://esgf.github.io/esg-search/ESGF_Search_RESTful_API.html
- [x] Discuss with Alan how to query/pull contents efficiently from the CEDA ESGF Index Node
- [x] Create the appropriate item-descriptions for building the records in our STAC index
- [x] Build an input plugin for ESGF CMIP6 and CMIP5 records. (NOTE: there is lots of non-CMIP data on ESGF, let's ignore that for now)
- [x] Build a media handler for esgf-solr
  - [ ] ~~item handler~~
  - [x] asset handler
- [x] Create a new "esgf-cmip" index to house this data
  - **Index names:**
    - `esgf-solr-assets-2022-03-10`
    - `esgf-solr-items-2022-03-10`
    - `esgf-solr-collections-2022-03-10`
- [x] Run the pipeline to load the records into STAC/Elasticsearch

The difference in converting from Solr to STAC items vs converting to Elasticsearch is the structure. Due to the different field types required for geo-spatial and temporal queries, the JSON structure differs slightly.

**Comment by Mahir-Sparkess** [comment]
- Asset-generator - media handler: https://github.com/cedadev/asset-generator/pull/25
- Asset-scanner - input plugin: https://github.com/cedadev/asset-scanner/pull/35
- Collection-generator: https://github.com/cedadev/collection-generator/pull/7
- Item-generator: https://github.com/cedadev/item-generator/pull/50
- item-description: [cmip6 deploy description](https://breezy.badc.rl.ac.uk/mrahman/stac-item-descriptions/-/blob/master/descriptions/CMIP6.yaml) and [description repository](https://github.com/Mahir-Sparkess/item-descriptions/tree/esgf-solr/descriptions)

Leaving a comment here to consolidate everything into one place.

**Comment by Mahir-Sparkess** [comment]
Current look at the generated ESGF Solr Asset:

```json 
{
    "id": "5390fa1d3d88b82fed027e90903e8eb7",
    "body": {
        "location": "CMIP6.AerChemMIP.BCC.BCC-ESM1.hist-piNTCF.r1i1p1f1.Amon.ch4.gn.v20190621.ch4_Amon_BCC-ESM1_hist-piNTCF_r1i1p1f1_gn_185001-201412.nc|esgf-data3.ceda.ac.uk",
        "size": 1232798772,
        "categories": [
            "data"
        ],
        "properties": {
            "mip_era": "CMIP6",
            "activity_id": "AerChemMIP",
            "institution_id": "BCC",
            "var_id": "hist-piNTCF.r1i1p1f1.Amon.ch4.gn.v20190621.ch4",
            "table_id": "Amon",
            "source_id": "BCC-ESM1",
            "experiment_id": "hist-piNTCF",
            "member_id": "r1i1p1f1",
            "grid_label": "gn"
        },
        "item_id": "4c21ef24a490c274746c8c30b88e1c9d"
    }
}
```

These are not all the mappings, only the DRS and size so far. Yet to decide what mappings to include (it is possible to have everything just in the properties)
